# Generated by Django 2.2 on 2020-04-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='评论对象ID')),
                ('body', models.TextField(help_text='内容', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
                ('author', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('content_type', models.ForeignKey(help_text='评论对象model', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, help_text='父评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='comment.Comment')),
                ('reply_to', models.ForeignKey(blank=True, help_text='回复给', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='userprofile.UserProfile')),
                ('root', models.ForeignKey(blank=True, help_text='根评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comment.Comment')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
