# Generated by Django 2.2 on 2020-04-15 00:03

import MyUtils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='演员', max_length=20)),
                ('des', models.TextField(help_text='简介', max_length=200)),
                ('create_at', models.DateTimeField(help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='专题', max_length=20)),
                ('des', models.TextField(max_length=200)),
                ('release_at', models.DateField(help_text='发布', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cover', MyUtils.fields.RestrictedFileField(help_text='封面', upload_to='movie/album')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='语种', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='片名', max_length=20)),
                ('des', models.TextField(help_text='简介')),
                ('dialogue', models.TextField(help_text='台词')),
                ('release_at', models.DateField(help_text='发布', null=True)),
                ('share_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
                ('cover', MyUtils.fields.RestrictedFileField(help_text='封面', upload_to='movie/pic')),
                ('file', MyUtils.fields.RestrictedFileField(help_text='视频', upload_to='movie/file')),
                ('actors', models.ManyToManyField(blank=True, help_text='演员表', to='movie.Actor')),
                ('album', models.ForeignKey(blank=True, help_text='专题', null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.MovieAlbum')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('language', models.ForeignKey(help_text='语种', on_delete=django.db.models.deletion.CASCADE, to='movie.MovieLanguage')),
                ('tags', models.ManyToManyField(help_text='标签', to='movie.MovieTag')),
                ('type', models.ForeignKey(help_text='类型', on_delete=django.db.models.deletion.CASCADE, to='movie.MovieType')),
            ],
            options={
                'ordering': ['-share_at'],
            },
        ),
    ]
