# Generated by Django 2.2 on 2020-04-15 00:03

import MyUtils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='专栏', max_length=10)),
                ('des', models.TextField(help_text='简介', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=20)),
                ('body', models.TextField(help_text='内容')),
                ('share_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='修改')),
                ('des', models.CharField(blank=True, help_text='简介', max_length=200, null=True)),
                ('pic', MyUtils.fields.RestrictedFileField(blank=True, help_text='图片', null=True, upload_to='article/pic')),
                ('album', models.ForeignKey(blank=True, help_text='专栏', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleAlbum')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('tags', models.ManyToManyField(help_text='标签', to='article.ArticleTag')),
                ('type', models.ForeignKey(help_text='类型', on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
            options={
                'ordering': ['-share_at'],
            },
        ),
    ]
