# Generated by Django 2.2 on 2020-04-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='点赞对象ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='点赞时间')),
                ('author', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('content_type', models.ForeignKey(help_text='点赞对象model', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='点赞对象ID')),
                ('liked_num', models.IntegerField(default=0, help_text='点赞数')),
                ('content_type', models.ForeignKey(help_text='点赞对象model', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-liked_num'],
            },
        ),
    ]
