# Generated by Django 2.2 on 2020-04-15 00:03

import MyUtils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='专辑', max_length=20)),
                ('des', models.TextField(max_length=200)),
                ('release_at', models.DateField(help_text='发布', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cover', MyUtils.fields.RestrictedFileField(help_text='封面', upload_to='music/album')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='语种', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='歌手', max_length=20)),
                ('des', models.TextField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='歌名', max_length=20)),
                ('lyrics', models.TextField(help_text='歌词')),
                ('release_at', models.DateField(help_text='发布', null=True)),
                ('share_at', models.DateTimeField(auto_now_add=True, help_text='创建')),
                ('cover', MyUtils.fields.RestrictedFileField(help_text='封面', upload_to='music/pic')),
                ('file', MyUtils.fields.RestrictedFileField(help_text='file', upload_to='music/file/songs')),
                ('mv', MyUtils.fields.RestrictedFileField(blank=True, help_text='MV', null=True, upload_to='music/file/mv')),
                ('album', models.ForeignKey(blank=True, help_text='专辑', null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MusicAlbum')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
                ('language', models.ForeignKey(help_text='语种', on_delete=django.db.models.deletion.CASCADE, to='music.MusicLanguage')),
                ('singer', models.ForeignKey(help_text='歌手', on_delete=django.db.models.deletion.CASCADE, to='music.Singer')),
                ('tags', models.ManyToManyField(help_text='标签', to='music.MusicTag')),
                ('type', models.ForeignKey(help_text='类型', on_delete=django.db.models.deletion.CASCADE, to='music.MusicType')),
            ],
            options={
                'ordering': ['-share_at'],
            },
        ),
    ]
